### ISSUE TITLE
use CSS to insert a middle-dot between tags in taglist

### ISSUE THREAD

**Issue by esdnm** [LukeSmithxyz/lugo#3]
Currently a middle-dot is inserted between tags in taglist by using HTML.

> https://github.com/LukeSmithxyz/lugo/blob/a56d5dafb2f5dd0ac2d77e60e4194999e82050aa/layouts/partials/footer.html#L9

Since the middle-dot is for stylistic reason, I propose it should be added via CSS using pseudo element. For example:

```css
.taglist a:not(:last-child)::after {
	content: " · "
}
```
I added a space before and after of `·`, it makes things look a bit nicer.
